In [2]:
import tensorflow.compat.v1 as tf

In [3]:
x1_data = [73., 93., 89., 96., 73]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed...
# 데이터 학습을 위해 적용할 실제 훈련셋
tf.disable_eager_execution()
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# 학습될 데이터 가 3개 이고, 출력될 데이터가 1개 이므로, 가중치는 3개
w1 = tf.Variable(tf.random.normal([1]), name='weight1')
w2 = tf.Variable(tf.random.normal([1]), name='weight2')
w3 = tf.Variable(tf.random.normal([1]), name='weight3')
b = tf.Variable(tf.random.normal([1]), name='bias')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [4]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3

# cost / loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small Learning rate for this data set
## Why?
# Optimizing! Gradient Descent-> 가중치 업데이트
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [5]:
# :Launch the graph in a session
sess = tf.Session()
#Init global variables in the graph (placeholder 초기화)
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  83384.8 
Prediction:
 [-102.53807  -125.027885 -122.40268  -131.71114   -97.113144]
10 Cost:  7.420064 
Prediction:
 [152.88702 181.99268 180.10144 197.70975 137.06685]
20 Cost:  6.628389 
Prediction:
 [153.6517  182.9278  181.01456 198.70444 137.78378]
30 Cost:  6.6006994 
Prediction:
 [153.64561 182.93643 181.0148  198.70508 137.79407]
40 Cost:  6.573161 
Prediction:
 [153.6372  182.94225 181.01231 198.7027  137.80219]
50 Cost:  6.5457563 
Prediction:
 [153.62885 182.94806 181.00984 198.70032 137.81029]
60 Cost:  6.5185013 
Prediction:
 [153.62048 182.95383 181.00734 198.69794 137.81836]
70 Cost:  6.49144 
Prediction:
 [153.61215 182.9596  181.00488 198.69559 137.8264 ]
80 Cost:  6.4644303 
Prediction:
 [153.60385 182.96536 181.00241 198.6932  137.83444]
90 Cost:  6.4376173 
Prediction:
 [153.59555 182.9711  180.99994 198.69087 137.84245]
100 Cost:  6.410943 
Prediction:
 [153.58728 182.9768  180.99748 198.6885  137.85043]
110 Cost:  6.384394 
Prediction:
 [153.57904 182.982

1120 Cost:  4.3109255 
Prediction:
 [152.85495 183.48471 180.78088 198.47388 138.56522]
1130 Cost:  4.295409 
Prediction:
 [152.84875 183.489   180.77904 198.472   138.57132]
1140 Cost:  4.2799377 
Prediction:
 [152.84258 183.4933  180.77722 198.47012 138.57742]
1150 Cost:  4.264592 
Prediction:
 [152.83641 183.49757 180.77542 198.46826 138.5835 ]
1160 Cost:  4.249265 
Prediction:
 [152.83026 183.50183 180.7736  198.46637 138.58957]
1170 Cost:  4.234081 
Prediction:
 [152.82416 183.5061  180.77182 198.46452 138.59561]
1180 Cost:  4.2189684 
Prediction:
 [152.81804 183.51031 180.77002 198.46266 138.60164]
1190 Cost:  4.2038865 
Prediction:
 [152.81195 183.51456 180.76822 198.4608  138.60767]
1200 Cost:  4.188894 
Prediction:
 [152.80588 183.5188  180.76645 198.45895 138.61368]
1210 Cost:  4.1739936 
Prediction:
 [152.7998  183.52298 180.76465 198.45709 138.61966]
1220 Cost:  4.159168 
Prediction:
 [152.79378 183.52719 180.76288 198.45526 138.62564]
1230 Cost:  4.1444244 
Prediction:
 [1

# Using Matrix for More Flexible

In [6]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# placeholders for a tensor
X_ = tf.placeholder(tf.float32, shape=[None, 3])
Y_ = tf.placeholder(tf.float32, shape=[None, 1])

W_ = tf.Variable(tf.random.normal([3, 1]), name='weight')
b_ = tf.Variable(tf.random.normal([1]), name='bias')

# Hypothesis
hypothesis_ = tf.matmul(X_, W_) + b_

# cost function
cost_ = tf.reduce_mean(tf.square(hypothesis_ - Y_))

# Minimize
optimizer_ = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train_ = optimizer_.minimize(cost_)

#Launch the graph
sess_ = tf.Session()
sess_.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val_, hy_val_, _ = sess_.run([cost_, hypothesis_, train_], feed_dict={X_: x_data, Y_: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val_, "\nPrediction:\n", hy_val_)

0 Cost:  5.470929 
Prediction:
 [[149.51395]
 [187.83185]
 [180.80145]
 [196.9575 ]
 [145.40524]]
10 Cost:  4.2291346 
Prediction:
 [[148.54486]
 [186.6522 ]
 [179.64688]
 [195.69923]
 [144.50255]]
20 Cost:  4.2071595 
Prediction:
 [[148.54976]
 [186.64323]
 [179.64578]
 [195.6971 ]
 [144.49283]]
30 Cost:  4.1853285 
Prediction:
 [[148.5576 ]
 [186.63788]
 [179.64821]
 [195.69878]
 [144.48584]]
40 Cost:  4.1635976 
Prediction:
 [[148.56543]
 [186.63252]
 [179.6506 ]
 [195.70045]
 [144.47887]]
50 Cost:  4.141986 
Prediction:
 [[148.57323]
 [186.62717]
 [179.653  ]
 [195.7021 ]
 [144.47191]]
60 Cost:  4.1205 
Prediction:
 [[148.58101]
 [186.62184]
 [179.6554 ]
 [195.70378]
 [144.46498]]
70 Cost:  4.099107 
Prediction:
 [[148.58878]
 [186.61653]
 [179.65778]
 [195.70544]
 [144.45805]]
80 Cost:  4.077849 
Prediction:
 [[148.59653]
 [186.61124]
 [179.66016]
 [195.70709]
 [144.45117]]
90 Cost:  4.0566993 
Prediction:
 [[148.60425]
 [186.60596]
 [179.66254]
 [195.70874]
 [144.44429]]
100 Cost

880 Cost:  2.7012055 
Prediction:
 [[149.15276]
 [186.23045]
 [179.83127]
 [195.82544]
 [143.95609]]
890 Cost:  2.6874938 
Prediction:
 [[149.15898]
 [186.2262 ]
 [179.83319]
 [195.82677]
 [143.95056]]
900 Cost:  2.6738446 
Prediction:
 [[149.16519]
 [186.22195]
 [179.83511]
 [195.8281 ]
 [143.94504]]
910 Cost:  2.6603127 
Prediction:
 [[149.17136]
 [186.21771]
 [179.837  ]
 [195.82938]
 [143.93954]]
920 Cost:  2.6467946 
Prediction:
 [[149.17755]
 [186.2135 ]
 [179.83891]
 [195.83069]
 [143.93405]]
930 Cost:  2.6333873 
Prediction:
 [[149.18369]
 [186.20927]
 [179.8408 ]
 [195.832  ]
 [143.92857]]
940 Cost:  2.6200466 
Prediction:
 [[149.18983]
 [186.2051 ]
 [179.84268]
 [195.8333 ]
 [143.92313]]
950 Cost:  2.6067796 
Prediction:
 [[149.19595]
 [186.2009 ]
 [179.84457]
 [195.8346 ]
 [143.9177 ]]
960 Cost:  2.593575 
Prediction:
 [[149.20206]
 [186.19672]
 [179.84645]
 [195.83588]
 [143.91226]]
970 Cost:  2.5804539 
Prediction:
 [[149.20815]
 [186.19255]
 [179.84833]
 [195.83716]
 [143

1790 Cost:  1.7134354 
Prediction:
 [[149.65546]
 [185.88646]
 [179.98607]
 [195.93135]
 [143.50983]]
1800 Cost:  1.7050674 
Prediction:
 [[149.66031]
 [185.88312]
 [179.98756]
 [195.93236]
 [143.50551]]
1810 Cost:  1.6967328 
Prediction:
 [[149.66518]
 [185.87982]
 [179.98907]
 [195.93338]
 [143.5012 ]]
1820 Cost:  1.6884327 
Prediction:
 [[149.67001]
 [185.87648]
 [179.99055]
 [195.9344 ]
 [143.4969 ]]
1830 Cost:  1.6801903 
Prediction:
 [[149.67485]
 [185.87318]
 [179.99205]
 [195.93541]
 [143.49263]]
1840 Cost:  1.672013 
Prediction:
 [[149.67964]
 [185.86989]
 [179.99352]
 [195.93639]
 [143.48836]]
1850 Cost:  1.6638663 
Prediction:
 [[149.68445]
 [185.86661]
 [179.995  ]
 [195.93741]
 [143.48412]]
1860 Cost:  1.6557379 
Prediction:
 [[149.68925]
 [185.86334]
 [179.99648]
 [195.93842]
 [143.47986]]
1870 Cost:  1.6476872 
Prediction:
 [[149.69402]
 [185.86006]
 [179.99796]
 [195.9394 ]
 [143.47563]]
1880 Cost:  1.6396633 
Prediction:
 [[149.69878]
 [185.8568 ]
 [179.9994 ]
 [195.94

## Reading Data from File

In [7]:
import tensorflow.compat.v1 as tf
import numpy as np

xy = np.loadtxt('resource/data-01-test-score.csv', delimiter=',', dtype=np.float32) #같은 데이터
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OL

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)


(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [8]:
# place holders for a tensor
tf.disable_eager_execution()
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b # X1W1 + X2W2 + X3W3 + b (행렬곱)

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)
        
    

0 Cost:  51858.66 
Prediction: 
 [[-68.24887 ]
 [-70.34999 ]
 [-75.565834]
 [-79.88053 ]
 [-52.673088]
 [-33.600212]]
10 Cost:  27.34849 
Prediction: 
 [[144.02405]
 [184.82274]
 [175.84073]
 [193.90257]
 [141.9623 ]
 [109.87376]]
20 Cost:  24.833307 
Prediction: 
 [[145.48355]
 [186.54047]
 [177.55246]
 [195.76176]
 [143.26736]
 [110.82391]]
30 Cost:  24.696264 
Prediction: 
 [[145.51526]
 [186.5417 ]
 [177.57307]
 [195.77933]
 [143.26315]
 [110.80891]]
40 Cost:  24.56016 
Prediction: 
 [[145.53723]
 [186.53134]
 [177.58223]
 [195.7844 ]
 [143.25014]
 [110.78742]]
50 Cost:  24.424978 
Prediction: 
 [[145.55907 ]
 [186.52095 ]
 [177.5913  ]
 [195.78938 ]
 [143.2371  ]
 [110.765976]]
60 Cost:  24.290648 
Prediction: 
 [[145.58083]
 [186.51057]
 [177.6003 ]
 [195.79434]
 [143.22412]
 [110.74458]]
70 Cost:  24.157175 
Prediction: 
 [[145.60252]
 [186.50027]
 [177.60928]
 [195.79929]
 [143.21118]
 [110.72326]]
80 Cost:  24.024635 
Prediction: 
 [[145.62411]
 [186.48996]
 [177.61823]
 [195.

760 Cost:  16.760588 
Prediction: 
 [[146.9382 ]
 [185.86613]
 [178.16434]
 [196.0972 ]
 [142.42241]
 [109.4044 ]]
770 Cost:  16.675829 
Prediction: 
 [[146.9554 ]
 [185.85799]
 [178.1715 ]
 [196.10094]
 [142.41237]
 [109.38732]]
780 Cost:  16.591639 
Prediction: 
 [[146.97255 ]
 [185.84987 ]
 [178.17867 ]
 [196.10468 ]
 [142.40237 ]
 [109.370316]]
790 Cost:  16.507933 
Prediction: 
 [[146.98965]
 [185.84181]
 [178.18579]
 [196.10838]
 [142.39243]
 [109.35334]]
800 Cost:  16.424835 
Prediction: 
 [[147.00668]
 [185.83372]
 [178.19287]
 [196.11209]
 [142.38249]
 [109.33643]]
810 Cost:  16.342205 
Prediction: 
 [[147.02367 ]
 [185.82571 ]
 [178.19997 ]
 [196.11578 ]
 [142.37262 ]
 [109.319565]]
820 Cost:  16.260157 
Prediction: 
 [[147.04059 ]
 [185.81772 ]
 [178.20703 ]
 [196.11948 ]
 [142.36276 ]
 [109.302765]]
830 Cost:  16.178568 
Prediction: 
 [[147.05746]
 [185.80974]
 [178.21408]
 [196.12312]
 [142.35294]
 [109.286  ]]
840 Cost:  16.097631 
Prediction: 
 [[147.07425]
 [185.80179]


1520 Cost:  11.646996 
Prediction: 
 [[148.09642]
 [185.32034]
 [178.64897]
 [196.34244]
 [141.75632]
 [108.24841]]
1530 Cost:  11.594892 
Prediction: 
 [[148.1098 ]
 [185.31404]
 [178.65459]
 [196.34517]
 [141.74873]
 [108.23496]]
1540 Cost:  11.543099 
Prediction: 
 [[148.12315]
 [185.3078 ]
 [178.66022]
 [196.3479 ]
 [141.74121]
 [108.22156]]
1550 Cost:  11.491639 
Prediction: 
 [[148.13646]
 [185.30157]
 [178.6658 ]
 [196.35062]
 [141.7337 ]
 [108.20819]]
1560 Cost:  11.440515 
Prediction: 
 [[148.1497 ]
 [185.29535]
 [178.67137]
 [196.35332]
 [141.72623]
 [108.19486]]
1570 Cost:  11.389736 
Prediction: 
 [[148.1629 ]
 [185.28915]
 [178.67691]
 [196.35602]
 [141.71877]
 [108.18158]]
1580 Cost:  11.339256 
Prediction: 
 [[148.17607]
 [185.283  ]
 [178.68246]
 [196.35869]
 [141.71135]
 [108.16834]]
1590 Cost:  11.289078 
Prediction: 
 [[148.1892  ]
 [185.27686 ]
 [178.68799 ]
 [196.36136 ]
 [141.70395 ]
 [108.155136]]
1600 Cost:  11.239238 
Prediction: 
 [[148.20229]
 [185.27074]
 [1

In [10]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis, feed_dict={X:[[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[197.99326]]
Other scores will be  [[181.07379]
 [168.30136]]


## Queue Runners! -> Data 관리

In [11]:
# 1 step : 사용할 파일들의 리스트를 만듦
filename_queue = tf.train.string_input_producer(['resource/data-01-test-score.csv'], shuffle=False, name='filename_queue')

# 2 step: Reader를 정의 (key, value)
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# 3 step 형태와 타입 정의 및 Decoding
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batche
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)



Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
Instructions for updating:
Queue-base

In [12]:
# place holders for a tensor
tf.disable_eager_execution()
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b # X1W1 + X2W2 + X3W3 + b (행렬곱)

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [14]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y:y_batch})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)
        
coord.request_stop()
coord.join(threads)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
0 Cost:  21205.836 
Prediction
 [[22.3801  ]
 [25.75621 ]
 [26.15255 ]
 [25.7417  ]
 [21.707424]
 [11.812565]
 [22.3801  ]
 [25.75621 ]
 [26.15255 ]
 [25.7417  ]]
10 Cost:  2.0037827 
Prediction
 [[153.0773 ]
 [182.85106]
 [180.93697]
 [194.30333]
 [141.52853]
 [100.13669]
 [153.0773 ]
 [182.85106]
 [180.93697]
 [194.30333]]
20 Cost:  1.6883703 
Prediction
 [[153.57361 ]
 [183.45465 ]
 [181.52798 ]
 [194.94786 ]
 [141.98985 ]
 [100.479004]
 [153.57361 ]
 [183.45465 ]
 [181.52798 ]
 [194.94786 ]]
30 Cost:  1.6834049 
Prediction
 [[153.57175]
 [183.45943]
 [181.52899]
 [194.94992]
 [141.99446]
 [100.48469]
 [153.57175]
 [183.45943]
 [181.52899]
 [194.94992]]
40 Cost:  1.6784874 
Prediction
 [[153.568   ]
 [183.4619  ]
 [181.52776 ]
 [194.94952 ]
 [141.9973  ]
 [100.489044]
 [153.568   ]
 [183.4619  ]
 [181.52776 ]
 [194.94952 ]]
50 Cost:  1.6736101 
Prediction
 [[153.56425]
 [183.46437]
 [181.52654]
 [194.

490 Cost:  1.4840801 
Prediction
 [[153.40984 ]
 [183.56596 ]
 [181.47545 ]
 [194.93271 ]
 [142.11655 ]
 [100.673035]
 [153.40984 ]
 [183.56596 ]
 [181.47545 ]
 [194.93271 ]]
500 Cost:  1.4802859 
Prediction
 [[153.40651 ]
 [183.5681  ]
 [181.47435 ]
 [194.93237 ]
 [142.11899 ]
 [100.676865]
 [153.40651 ]
 [183.5681  ]
 [181.47435 ]
 [194.93237 ]]
510 Cost:  1.4765387 
Prediction
 [[153.40324]
 [183.57025]
 [181.47327]
 [194.93204]
 [142.12144]
 [100.68067]
 [153.40324]
 [183.57025]
 [181.47327]
 [194.93204]]
520 Cost:  1.4728107 
Prediction
 [[153.39998]
 [183.5724 ]
 [181.4722 ]
 [194.9317 ]
 [142.12389]
 [100.68448]
 [153.39998]
 [183.5724 ]
 [181.4722 ]
 [194.9317 ]]
530 Cost:  1.469096 
Prediction
 [[153.39673]
 [183.57454]
 [181.47112]
 [194.93138]
 [142.12633]
 [100.68828]
 [153.39673]
 [183.57454]
 [181.47112]
 [194.93138]]
540 Cost:  1.4653956 
Prediction
 [[153.39346]
 [183.57666]
 [181.47002]
 [194.93103]
 [142.12874]
 [100.69207]
 [153.39346]
 [183.57666]
 [181.47002]
 [194

1010 Cost:  1.313828 
Prediction
 [[153.25114 ]
 [183.6698  ]
 [181.42264 ]
 [194.91696 ]
 [142.23433 ]
 [100.858444]
 [153.25114 ]
 [183.6698  ]
 [181.42264 ]
 [194.91696 ]]
1020 Cost:  1.311023 
Prediction
 [[153.24834]
 [183.67166]
 [181.4217 ]
 [194.9167 ]
 [142.23642]
 [100.86176]
 [153.24834]
 [183.67166]
 [181.4217 ]
 [194.9167 ]]
1030 Cost:  1.3082148 
Prediction
 [[153.2455 ]
 [183.67348]
 [181.42073]
 [194.91643]
 [142.23846]
 [100.86504]
 [153.2455 ]
 [183.67348]
 [181.42073]
 [194.91643]]
1040 Cost:  1.3054644 
Prediction
 [[153.24272]
 [183.67532]
 [181.41982]
 [194.91615]
 [142.24054]
 [100.86833]
 [153.24272]
 [183.67532]
 [181.41982]
 [194.91615]]
1050 Cost:  1.3027097 
Prediction
 [[153.23993]
 [183.67714]
 [181.4189 ]
 [194.91592]
 [142.2426 ]
 [100.87163]
 [153.23993]
 [183.67714]
 [181.4189 ]
 [194.91592]]
1060 Cost:  1.2999405 
Prediction
 [[153.23712 ]
 [183.67897 ]
 [181.41794 ]
 [194.91565 ]
 [142.24463 ]
 [100.874886]
 [153.23712 ]
 [183.67897 ]
 [181.41794 ]
 

1540 Cost:  1.1850576 
Prediction
 [[153.11247 ]
 [183.76012 ]
 [181.37611 ]
 [194.90446 ]
 [142.33545 ]
 [101.021545]
 [153.11247 ]
 [183.76012 ]
 [181.37611 ]
 [194.90446 ]]
1550 Cost:  1.182977 
Prediction
 [[153.11003]
 [183.76167]
 [181.37529]
 [194.90424]
 [142.33717]
 [101.0244 ]
 [153.11003]
 [183.76167]
 [181.37529]
 [194.90424]]
1560 Cost:  1.1809117 
Prediction
 [[153.10762 ]
 [183.76323 ]
 [181.37448 ]
 [194.90404 ]
 [142.33891 ]
 [101.027245]
 [153.10762 ]
 [183.76323 ]
 [181.37448 ]
 [194.90404 ]]
1570 Cost:  1.1788561 
Prediction
 [[153.10522]
 [183.76479]
 [181.37366]
 [194.90382]
 [142.34064]
 [101.03007]
 [153.10522]
 [183.76479]
 [181.37366]
 [194.90382]]
1580 Cost:  1.1768242 
Prediction
 [[153.10284 ]
 [183.76634 ]
 [181.37286 ]
 [194.90363 ]
 [142.34238 ]
 [101.032906]
 [153.10284 ]
 [183.76634 ]
 [181.37286 ]
 [194.90363 ]]
1590 Cost:  1.1748012 
Prediction
 [[153.10043]
 [183.76787]
 [181.37206]
 [194.9034 ]
 [142.34407]
 [101.03571]
 [153.10043]
 [183.76787]
 [